### ISSUE TITLE
Drop the database

### ISSUE THREAD

**Issue by PopSergiuFlorin** [gilf/angular2-indexeddb#10]
How can I drop the database schema, in this case the object store? I want to recreate each time the object store.

**Comment by gilf** [comment]
Hi @PopSergiuFlorin,

In order to change IndexedDB database schema you need to make a version change. A version change will trigger the onupgradeneeded event and inside of it you can make changes such as removing an objectStore using the [removeObjectStore](https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/deleteObjectStore) function.  
In angular2-indexeddb you can achieve that with the createStore function. Just change the version number and in it's upgrade callback use the deleteObjectStore function.

I hope that it will help you.
