### ISSUE TITLE
Failed to execute 'createIndex' on 'IDBObjectStore'

### ISSUE THREAD

**Issue by sasanazizi** [gilf/angular2-indexeddb#21]
i want to create an object with createStore but it failure
error contains :  The keyPath argument contains an invalid key path
anyone can hears me ?!

**Comment by gilf** [comment]
When you create an objectStore it should follow some restrictions. The error you are getting is caused by invalid key path that you provided as the key of the objectStore. 
"A valid key path is one of:
* An empty DOMString.
* A DOMString containing a JavaScript identifier [ECMA-262].
* A DOMString containing multiple Javascript identifiers separated by periods (ASCII character code 46) [ECMA-262].
* A non-empty Array containing only DOMStrings conforming to the above requirements."

Numeric indexes are not valid JavaScript identifiers so do not form parts of a valid key path. Similarly, you couldn't reference the properties obj["abc def"] or obj["ghi.jkl"] with key paths as defined in the current version of the Indexed DB specification."
