### ISSUE TITLE
Having trouble to insert new value.

### ISSUE THREAD

**Issue by altaf933** [gilf/angular2-indexeddb#23]
Every time when I add new value into database that returned below error. 

> DOMException: Failed to execute 'add' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.

Here is the code snippet that I used for insert new value.

```
let db = new AngularIndexedDB('myDb', 1);

    db.createStore(1, (evt) => {
      const objectStore = evt.currentTarget.result.createObjectStore('people', { keyPath: 'id', unique: true });
      objectStore.createIndex("name", "name", { unique: false });
      objectStore.createIndex("email", "email", { unique: true });

    }).then(() => {
      db.add('people', { name: "test", email: "test" }).then(() => {
      }, (error) => {
        console.log(error);
      });

    }, (error) => {
      console.log(error);
    });
```
Would you please help to resolve this issue ?

**Comment by gilf** [comment]
Hi,

Sorry for the late response.

In the createStore callback function you are creating a new objectStore and you indicate a keypath which is id and it should be unique. The key path isn't auto generated if you don't specify autoIncrement in the configuration object. Therefore, when you are trying to use the add function you should also pass a third argument which is the key or else the passed key will be undefined and the function will raise the error you got. 
You can use the following code instead of line 4 in your cofde and make the key auto generated and then your code will work:
`let objectStore = evt.currentTarget.result.createObjectStore( 'people', { keyPath: "id", autoIncrement: true });`

I hope this answer will help you.

Best Regards,
Gil
