### ISSUE TITLE
Error: use the createStore function to create a database

### ISSUE THREAD

**Issue by pyarun** [gilf/angular2-indexeddb#28]
I am getting this error

> You need to use the createStore function to create a database before you query it!

[my service](https://pastebin.com/JdZ9m2hc)

in the constructor i am calling createStore. I call `listOrgs` function from Component. When i reload the browser i get the above error. 
Not able to figure out how to fix it.

Please help.

**Comment by gilf** [comment]
Hi,

Do you have binding to one of the public functions you wrote in your component template? (if yes try to add the async pipe to it).
I'm asking that question because the createStore is an async function and therefore it takes some time to open the db for work. If the functions are being called before the db is open then you will get the error (it's a race condition).

**Comment by thiagoalmedeiros** [comment]
@gilf I have a similar problem ... I have a service that is responsible for creating the bank and a method that makes a getAll in the bank ... With this it pops this error:

Error: Uncaught (in promise): You need to use the createStore function to create a database before you query it!

But the BD have created, I have already done some insertions in it.

This is my component:

https://1drv.ms/u/s!AkjvI2Itb3s0gY1BM_ucRKKntHRi_A

and this is my service:
https://1drv.ms/u/s!AkjvI2Itb3s0gY1CbQIorAfyS44_4A

**Comment by gilf** [comment]
@thiagoalmedeiros 
You are probably having a race condition between the creation of the database (which occurs in the constructor) and the call to getAll. The reason of the race condition is that both of the functions are async and you should run the getAll after createDatabase finished (which probably isn't happening in your code).
