### ISSUE TITLE
[Feature Request] getAll option to set a offset or number of records 

### ISSUE THREAD

**Issue by zeet2020** [gilf/angular2-indexeddb#7]
getALL method currently fetch all records from Objectstore, need a features to set the offset and number of iteration or records needed

**Comment by gilf** [comment]
Hi @zeet2020,

Thanks for the request. That functionality can be achieved using [IDBKeyRange](https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange). 
When I'll have spare time, I'll work on adding a new get function that receives step and top arguments and outputs only the relevant records in the range.

**Comment by gilf** [comment]
Hi @zeet2020,
 
You can use the getAll or openCursor functions with an IDBKeyRange object argument now

**Comment by zeet2020** [comment]
hi @gif,

that is a real help, by if am not wrong IDBKeyRange, your need to know the keyRange to startWith and endWith key. to define the IDBKeyRange. but if your use uuid as a key. to create record or object. we can't really use IDBkeyRange to fetch a range of objects.

**Comment by gilf** [comment]
Hi @zeet2020,

I know it isn't a perfect solution but if you now the offset and the number of needed records it's sufficient if the key is of type number. 
In other scenarios a new function should be introduced in the library API which enables query types. Since such a function is not something that I can implement fast I preferred to add the key range option for now and later implement a query function.
